/*
 * This file is generated by jOOQ.
*/
package com.exploration.jooq;


import com.exploration.jooq.tables.Nearearthasteroids;
import com.exploration.jooq.tables.Resources;
import com.exploration.jooq.tables.Spacecraftrentalrecords;
import com.exploration.jooq.tables.Spacecrafts;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>db21</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NEAREARTHASTEROIDS_PRIMARY = Indexes0.NEAREARTHASTEROIDS_PRIMARY;
    public static final Index NEAREARTHASTEROIDS_RESOURCETYPE = Indexes0.NEAREARTHASTEROIDS_RESOURCETYPE;
    public static final Index RESOURCES_PRIMARY = Indexes0.RESOURCES_PRIMARY;
    public static final Index SPACECRAFTRENTALRECORDS_PRIMARY = Indexes0.SPACECRAFTRENTALRECORDS_PRIMARY;
    public static final Index SPACECRAFTS_PRIMARY = Indexes0.SPACECRAFTS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index NEAREARTHASTEROIDS_PRIMARY = Internal.createIndex("PRIMARY", Nearearthasteroids.NEAREARTHASTEROIDS, new OrderField[] { Nearearthasteroids.NEAREARTHASTEROIDS.NEAID }, true);
        public static Index NEAREARTHASTEROIDS_RESOURCETYPE = Internal.createIndex("ResourceType", Nearearthasteroids.NEAREARTHASTEROIDS, new OrderField[] { Nearearthasteroids.NEAREARTHASTEROIDS.RESOURCETYPE }, false);
        public static Index RESOURCES_PRIMARY = Internal.createIndex("PRIMARY", Resources.RESOURCES, new OrderField[] { Resources.RESOURCES.TYPE }, true);
        public static Index SPACECRAFTRENTALRECORDS_PRIMARY = Internal.createIndex("PRIMARY", Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS, new OrderField[] { Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.AGENCYNAME, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.MODELID, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.SPACECRAFTINDEX }, true);
        public static Index SPACECRAFTS_PRIMARY = Internal.createIndex("PRIMARY", Spacecrafts.SPACECRAFTS, new OrderField[] { Spacecrafts.SPACECRAFTS.AGENCYNAME, Spacecrafts.SPACECRAFTS.MODELID }, true);
    }
}
