/*
 * This file is generated by jOOQ.
*/
package com.exploration.jooq;


import com.exploration.jooq.tables.Nearearthasteroids;
import com.exploration.jooq.tables.Resources;
import com.exploration.jooq.tables.Spacecraftrentalrecords;
import com.exploration.jooq.tables.Spacecrafts;
import com.exploration.jooq.tables.records.NearearthasteroidsRecord;
import com.exploration.jooq.tables.records.ResourcesRecord;
import com.exploration.jooq.tables.records.SpacecraftrentalrecordsRecord;
import com.exploration.jooq.tables.records.SpacecraftsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>db21</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NearearthasteroidsRecord> KEY_NEAREARTHASTEROIDS_PRIMARY = UniqueKeys0.KEY_NEAREARTHASTEROIDS_PRIMARY;
    public static final UniqueKey<ResourcesRecord> KEY_RESOURCES_PRIMARY = UniqueKeys0.KEY_RESOURCES_PRIMARY;
    public static final UniqueKey<SpacecraftrentalrecordsRecord> KEY_SPACECRAFTRENTALRECORDS_PRIMARY = UniqueKeys0.KEY_SPACECRAFTRENTALRECORDS_PRIMARY;
    public static final UniqueKey<SpacecraftsRecord> KEY_SPACECRAFTS_PRIMARY = UniqueKeys0.KEY_SPACECRAFTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<NearearthasteroidsRecord, ResourcesRecord> NEAREARTHASTEROIDS_IBFK_1 = ForeignKeys0.NEAREARTHASTEROIDS_IBFK_1;
    public static final ForeignKey<SpacecraftrentalrecordsRecord, SpacecraftsRecord> SPACECRAFTRENTALRECORDS_IBFK_1 = ForeignKeys0.SPACECRAFTRENTALRECORDS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<NearearthasteroidsRecord> KEY_NEAREARTHASTEROIDS_PRIMARY = Internal.createUniqueKey(Nearearthasteroids.NEAREARTHASTEROIDS, "KEY_NearEarthAsteroids_PRIMARY", Nearearthasteroids.NEAREARTHASTEROIDS.NEAID);
        public static final UniqueKey<ResourcesRecord> KEY_RESOURCES_PRIMARY = Internal.createUniqueKey(Resources.RESOURCES, "KEY_Resources_PRIMARY", Resources.RESOURCES.TYPE);
        public static final UniqueKey<SpacecraftrentalrecordsRecord> KEY_SPACECRAFTRENTALRECORDS_PRIMARY = Internal.createUniqueKey(Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS, "KEY_SpacecraftRentalRecords_PRIMARY", Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.AGENCYNAME, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.MODELID, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.SPACECRAFTINDEX);
        public static final UniqueKey<SpacecraftsRecord> KEY_SPACECRAFTS_PRIMARY = Internal.createUniqueKey(Spacecrafts.SPACECRAFTS, "KEY_Spacecrafts_PRIMARY", Spacecrafts.SPACECRAFTS.AGENCYNAME, Spacecrafts.SPACECRAFTS.MODELID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<NearearthasteroidsRecord, ResourcesRecord> NEAREARTHASTEROIDS_IBFK_1 = Internal.createForeignKey(com.exploration.jooq.Keys.KEY_RESOURCES_PRIMARY, Nearearthasteroids.NEAREARTHASTEROIDS, "NearEarthAsteroids_ibfk_1", Nearearthasteroids.NEAREARTHASTEROIDS.RESOURCETYPE);
        public static final ForeignKey<SpacecraftrentalrecordsRecord, SpacecraftsRecord> SPACECRAFTRENTALRECORDS_IBFK_1 = Internal.createForeignKey(com.exploration.jooq.Keys.KEY_SPACECRAFTS_PRIMARY, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS, "SpacecraftRentalRecords_ibfk_1", Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.AGENCYNAME, Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.MODELID);
    }
}
