/*
 * This file is generated by jOOQ.
*/
package com.exploration.jooq;


import com.exploration.jooq.tables.Nearearthasteroids;
import com.exploration.jooq.tables.Resources;
import com.exploration.jooq.tables.Spacecraftrentalrecords;
import com.exploration.jooq.tables.Spacecrafts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db21
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db21.NearEarthAsteroids</code>.
     */
    public static final Nearearthasteroids NEAREARTHASTEROIDS = com.exploration.jooq.tables.Nearearthasteroids.NEAREARTHASTEROIDS;

    /**
     * The table <code>db21.Resources</code>.
     */
    public static final Resources RESOURCES = com.exploration.jooq.tables.Resources.RESOURCES;

    /**
     * The table <code>db21.SpacecraftRentalRecords</code>.
     */
    public static final Spacecraftrentalrecords SPACECRAFTRENTALRECORDS = com.exploration.jooq.tables.Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS;

    /**
     * The table <code>db21.Spacecrafts</code>.
     */
    public static final Spacecrafts SPACECRAFTS = com.exploration.jooq.tables.Spacecrafts.SPACECRAFTS;
}
