/*
 * This file is generated by jOOQ.
*/
package com.exploration.jooq.tables.records;


import com.exploration.jooq.tables.Spacecraftrentalrecords;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpacecraftrentalrecordsRecord extends UpdatableRecordImpl<SpacecraftrentalrecordsRecord> implements Record5<String, String, Integer, Date, Date> {

    private static final long serialVersionUID = -175548171;

    /**
     * Setter for <code>db21.SpacecraftRentalRecords.AgencyName</code>.
     */
    public void setAgencyname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>db21.SpacecraftRentalRecords.AgencyName</code>.
     */
    public String getAgencyname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>db21.SpacecraftRentalRecords.ModelId</code>.
     */
    public void setModelid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db21.SpacecraftRentalRecords.ModelId</code>.
     */
    public String getModelid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db21.SpacecraftRentalRecords.SpacecraftIndex</code>.
     */
    public void setSpacecraftindex(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db21.SpacecraftRentalRecords.SpacecraftIndex</code>.
     */
    public Integer getSpacecraftindex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db21.SpacecraftRentalRecords.CheckoutDate</code>.
     */
    public void setCheckoutdate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>db21.SpacecraftRentalRecords.CheckoutDate</code>.
     */
    public Date getCheckoutdate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>db21.SpacecraftRentalRecords.ReturnDate</code>.
     */
    public void setReturndate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>db21.SpacecraftRentalRecords.ReturnDate</code>.
     */
    public Date getReturndate() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Date, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Date, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.AGENCYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.MODELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.SPACECRAFTINDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.CHECKOUTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS.RETURNDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAgencyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSpacecraftindex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getCheckoutdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getReturndate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAgencyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSpacecraftindex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCheckoutdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getReturndate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord value1(String value) {
        setAgencyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord value2(String value) {
        setModelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord value3(Integer value) {
        setSpacecraftindex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord value4(Date value) {
        setCheckoutdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord value5(Date value) {
        setReturndate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpacecraftrentalrecordsRecord values(String value1, String value2, Integer value3, Date value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpacecraftrentalrecordsRecord
     */
    public SpacecraftrentalrecordsRecord() {
        super(Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS);
    }

    /**
     * Create a detached, initialised SpacecraftrentalrecordsRecord
     */
    public SpacecraftrentalrecordsRecord(String agencyname, String modelid, Integer spacecraftindex, Date checkoutdate, Date returndate) {
        super(Spacecraftrentalrecords.SPACECRAFTRENTALRECORDS);

        set(0, agencyname);
        set(1, modelid);
        set(2, spacecraftindex);
        set(3, checkoutdate);
        set(4, returndate);
    }
}
