/*
 * This file is generated by jOOQ.
*/
package com.exploration.jooq.tables;


import com.exploration.jooq.Db21;
import com.exploration.jooq.Indexes;
import com.exploration.jooq.Keys;
import com.exploration.jooq.tables.records.NearearthasteroidsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nearearthasteroids extends TableImpl<NearearthasteroidsRecord> {

    private static final long serialVersionUID = -1622935867;

    /**
     * The reference instance of <code>db21.NearEarthAsteroids</code>
     */
    public static final Nearearthasteroids NEAREARTHASTEROIDS = new Nearearthasteroids();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NearearthasteroidsRecord> getRecordType() {
        return NearearthasteroidsRecord.class;
    }

    /**
     * The column <code>db21.NearEarthAsteroids.NeaId</code>.
     */
    public final TableField<NearearthasteroidsRecord, String> NEAID = createField("NeaId", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>db21.NearEarthAsteroids.Distance</code>.
     */
    public final TableField<NearearthasteroidsRecord, Double> DISTANCE = createField("Distance", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>db21.NearEarthAsteroids.Family</code>.
     */
    public final TableField<NearearthasteroidsRecord, String> FAMILY = createField("Family", org.jooq.impl.SQLDataType.CHAR(6), this, "");

    /**
     * The column <code>db21.NearEarthAsteroids.MinDuration</code>.
     */
    public final TableField<NearearthasteroidsRecord, Integer> MINDURATION = createField("MinDuration", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db21.NearEarthAsteroids.MinEnergy</code>.
     */
    public final TableField<NearearthasteroidsRecord, Double> MINENERGY = createField("MinEnergy", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>db21.NearEarthAsteroids.ResourceType</code>.
     */
    public final TableField<NearearthasteroidsRecord, String> RESOURCETYPE = createField("ResourceType", org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * Create a <code>db21.NearEarthAsteroids</code> table reference
     */
    public Nearearthasteroids() {
        this(DSL.name("NearEarthAsteroids"), null);
    }

    /**
     * Create an aliased <code>db21.NearEarthAsteroids</code> table reference
     */
    public Nearearthasteroids(String alias) {
        this(DSL.name(alias), NEAREARTHASTEROIDS);
    }

    /**
     * Create an aliased <code>db21.NearEarthAsteroids</code> table reference
     */
    public Nearearthasteroids(Name alias) {
        this(alias, NEAREARTHASTEROIDS);
    }

    private Nearearthasteroids(Name alias, Table<NearearthasteroidsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Nearearthasteroids(Name alias, Table<NearearthasteroidsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Db21.DB21;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NEAREARTHASTEROIDS_PRIMARY, Indexes.NEAREARTHASTEROIDS_RESOURCETYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NearearthasteroidsRecord> getPrimaryKey() {
        return Keys.KEY_NEAREARTHASTEROIDS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NearearthasteroidsRecord>> getKeys() {
        return Arrays.<UniqueKey<NearearthasteroidsRecord>>asList(Keys.KEY_NEAREARTHASTEROIDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<NearearthasteroidsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NearearthasteroidsRecord, ?>>asList(Keys.NEAREARTHASTEROIDS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Nearearthasteroids as(String alias) {
        return new Nearearthasteroids(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Nearearthasteroids as(Name alias) {
        return new Nearearthasteroids(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Nearearthasteroids rename(String name) {
        return new Nearearthasteroids(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Nearearthasteroids rename(Name name) {
        return new Nearearthasteroids(name, null);
    }
}
